// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ThulasirajKomminar.InfluxDB
{
    public static class GetBucket
    {
        public static Task<GetBucketResult> InvokeAsync(GetBucketArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBucketResult>("influxdb:index/getBucket:getBucket", args ?? new GetBucketArgs(), options.WithDefaults());

        public static Output<GetBucketResult> Invoke(GetBucketInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBucketResult>("influxdb:index/getBucket:getBucket", args ?? new GetBucketInvokeArgs(), options.WithDefaults());

        public static Output<GetBucketResult> Invoke(GetBucketInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetBucketResult>("influxdb:index/getBucket:getBucket", args ?? new GetBucketInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetBucketArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetBucketArgs()
        {
        }
        public static new GetBucketArgs Empty => new GetBucketArgs();
    }

    public sealed class GetBucketInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetBucketInvokeArgs()
        {
        }
        public static new GetBucketInvokeArgs Empty => new GetBucketInvokeArgs();
    }


    [OutputType]
    public sealed class GetBucketResult
    {
        public readonly string CreatedAt;
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;
        public readonly string OrgId;
        public readonly int RetentionPeriod;
        public readonly string Type;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetBucketResult(
            string createdAt,

            string description,

            string id,

            string name,

            string orgId,

            int retentionPeriod,

            string type,

            string updatedAt)
        {
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Name = name;
            OrgId = orgId;
            RetentionPeriod = retentionPeriod;
            Type = type;
            UpdatedAt = updatedAt;
        }
    }
}
