// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package influxdb

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/thulasirajkomminar/pulumi-influxdb/sdk/go/influxdb/internal"
)

func LookupBucket(ctx *pulumi.Context, args *LookupBucketArgs, opts ...pulumi.InvokeOption) (*LookupBucketResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupBucketResult
	err := ctx.Invoke("influxdb:index/getBucket:getBucket", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBucket.
type LookupBucketArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getBucket.
type LookupBucketResult struct {
	CreatedAt       string `pulumi:"createdAt"`
	Description     string `pulumi:"description"`
	Id              string `pulumi:"id"`
	Name            string `pulumi:"name"`
	OrgId           string `pulumi:"orgId"`
	RetentionPeriod int    `pulumi:"retentionPeriod"`
	Type            string `pulumi:"type"`
	UpdatedAt       string `pulumi:"updatedAt"`
}

func LookupBucketOutput(ctx *pulumi.Context, args LookupBucketOutputArgs, opts ...pulumi.InvokeOption) LookupBucketResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupBucketResultOutput, error) {
			args := v.(LookupBucketArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("influxdb:index/getBucket:getBucket", args, LookupBucketResultOutput{}, options).(LookupBucketResultOutput), nil
		}).(LookupBucketResultOutput)
}

// A collection of arguments for invoking getBucket.
type LookupBucketOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupBucketOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBucketArgs)(nil)).Elem()
}

// A collection of values returned by getBucket.
type LookupBucketResultOutput struct{ *pulumi.OutputState }

func (LookupBucketResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupBucketResult)(nil)).Elem()
}

func (o LookupBucketResultOutput) ToLookupBucketResultOutput() LookupBucketResultOutput {
	return o
}

func (o LookupBucketResultOutput) ToLookupBucketResultOutputWithContext(ctx context.Context) LookupBucketResultOutput {
	return o
}

func (o LookupBucketResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBucketResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupBucketResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBucketResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupBucketResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBucketResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupBucketResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBucketResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupBucketResultOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBucketResult) string { return v.OrgId }).(pulumi.StringOutput)
}

func (o LookupBucketResultOutput) RetentionPeriod() pulumi.IntOutput {
	return o.ApplyT(func(v LookupBucketResult) int { return v.RetentionPeriod }).(pulumi.IntOutput)
}

func (o LookupBucketResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBucketResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o LookupBucketResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupBucketResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupBucketResultOutput{})
}
