// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBucket(args: GetBucketArgs, opts?: pulumi.InvokeOptions): Promise<GetBucketResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("influxdb:index/getBucket:getBucket", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getBucket.
 */
export interface GetBucketArgs {
    name: string;
}

/**
 * A collection of values returned by getBucket.
 */
export interface GetBucketResult {
    readonly createdAt: string;
    readonly description: string;
    readonly id: string;
    readonly name: string;
    readonly orgId: string;
    readonly retentionPeriod: number;
    readonly type: string;
    readonly updatedAt: string;
}
export function getBucketOutput(args: GetBucketOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBucketResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("influxdb:index/getBucket:getBucket", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getBucket.
 */
export interface GetBucketOutputArgs {
    name: pulumi.Input<string>;
}
