// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getLabel(args: GetLabelArgs, opts?: pulumi.InvokeOptions): Promise<GetLabelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("influxdb:index/getLabel:getLabel", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getLabel.
 */
export interface GetLabelArgs {
    id: string;
}

/**
 * A collection of values returned by getLabel.
 */
export interface GetLabelResult {
    readonly id: string;
    readonly name: string;
    readonly orgId: string;
    readonly properties: {[key: string]: string};
}
export function getLabelOutput(args: GetLabelOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLabelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("influxdb:index/getLabel:getLabel", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getLabel.
 */
export interface GetLabelOutputArgs {
    id: pulumi.Input<string>;
}
